CREATE TABLE `space_product_bill_of_material_header_data`
(
  `BillOfMaterial`                   varchar(20) NOT NULL,
  `BillOfMaterialCategory`           varchar(6) NOT NULL,
  `BillOfMaterialVariant`            varchar(6) NOT NULL,
  `BillOfMaterialVersion`            varchar(6) NOT NULL,
  `ChangeDocument`                   varchar(10) NOT NULL,
  `SpaceProduct`                     varchar(20) DEFAULT NULL,
  `BaseCamp`                         varchar(20) DEFAULT NULL,
  `BillOfMaterialVariantUsage`       varchar(6) DEFAULT NULL,
  `IsMultipleBOMAlt`                 tinyint(1) DEFAULT NULL,
  `BOMHeaderInternalChangeCount`     varchar(20) DEFAULT NULL,
  `BOMUsagePriority`                 varchar(20) DEFAULT NULL,
  `BillOfMaterialAuthsnGrp`          varchar(20) DEFAULT NULL,
  `BOMVersionStatus`                 varchar(20) DEFAULT NULL,
  `IsVersionBillOfMaterial`          tinyint(1) DEFAULT NULL,
  `IsLatestBOMVersion`               tinyint(1) DEFAULT NULL,
  `BOMHeaderText`                    varchar(40) DEFAULT NULL,
  `BOMAlternativeText`               varchar(40) DEFAULT NULL,
  `BillOfMaterialStatus`             varchar(20) DEFAULT NULL,
  `HeaderValidityStartDate`          varchar(20) DEFAULT NULL,
  `HeaderValidityEndDate`            varchar(20) DEFAULT NULL,
  `MinimumLotSizeQuantity`           varchar(20) DEFAULT NULL,
  `MaximumLotSizeQuantity`           varchar(20) DEFAULT NULL,
  `BOMHeaderBaseUnit`                varchar(20) DEFAULT NULL,
  `BOMHeaderQuantityInBaseUnit`      varchar(20) DEFAULT NULL,
  `SpaceProductDescription`          varchar(40) DEFAULT NULL,
  `BaseCampName`                     varchar(30) DEFAULT NULL,
  `BillOfMaterialHdrDetailsText`     varchar(20) DEFAULT NULL,
  `CreatedDateTime`                  varchar(20) DEFAULT NULL,
  `LastModifiedDateTime`             varchar(20) DEFAULT NULL,
    PRIMARY KEY (`BillOfMaterial`, `BillOfMaterialCategory`, `BillOfMaterialVariant`, `BillOfMaterialVersion`, `ChangeDocument`)
) ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4;
